### ISSUE TITLE
Undefined constant "settings"

### ISSUE THREAD

**Issue by ikx94** [ibnsultan/flow#1]
First of all, what you are making looks great. I was looking into Leaf PHP and found your repo.

I am getting this error when trying to open the login or register page, or any other page that calls for settings.

"Undefined constant "settings" (View: C:\laragon\www\flow\app\views\auth\login.blade.php)"

Comes from this: 								<img src="{{ settings->get('logo_dark') }}" class="w-25" alt="img">

I ran composer install, and pnpm install.

I ran the migration and seeded the database.

In settings, logo_dark has this value: /assets/images/brand/logo.png

Another problem that I'm running into is that the styles.css isn't loaded, it returns a 404.

<link rel="stylesheet" href="{{ assets('css/styles.css') }}">

That isn't working for some reason.

I set public as the root folder.

Using Laragon with Apache:

define ROOT "C:/laragon/www/flow/public"
define SITE "flow.test"

Also tried to serve the site with leaf serve, same errors.

Do you have any hints on how to fix it?

Your project is looking great, thank you in advance.

**Comment by ibnsultan** [comment]
I am aware of the issue, I had actually fixed it and several others in `dev-main` but didn't make an actual release on them

use the command
`composer create-project ibnsultan/flow:dev-main <YOUR_PROJECT>`

Just to note, flow is still in active developement, while it's stable to some extent there's a likelihood to be several issues and upcoming breaking changes.
